apiVersion: v1
kind: ServiceAccount
metadata:
  name: memcached-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcached-role
rules:
  - apiGroups:
      - cache.landomfreedom.ru
    resources:
      - memcacheds
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cache.landomfreedom.ru
    resources:
      - memcacheds/finalizers
    verbs:
      - update
  - apiGroups:
      - cache.landomfreedom.ru
    resources:
      - memcacheds/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - put
      - use
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - watch
      - create
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: memcached-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: memcached-role
subjects:
  - kind: ServiceAccount
    name: memcached-operator
    namespace: default